### ISSUE TITLE
Can I sign a transaction like this?

### ISSUE THREAD

**Issue by chris41188** [LedgerHQ/ledger-wallet-api#4]
Hi I represent the counterparty community and we are looking for a hardware wallet that will allow us to store your counterparty tokens, and also spend them

I am thinking if I send my counterparty tokens to a ledger address and make a note of the path of the address, I should be able to make a transaction that spends them and have the ledger sign it

here is an example transaction to be signed, seems like I can sign the inputs and outputs using
Ledger.signP2SH(inputs, scripts, outputs_number, outputs_script, paths)

before I purchase a ledger to try this, am I correct in my thinking? after all counterparty txs are just bitcoin transactions

{
   "lock_time":0,
   "size":381,
   "inputs":[
      {
         "prev_out":{
            "index":0,
            "hash":"459eee043d30b29c4f9e9b3b55af78f5b4fe4bd818bee49a4b75becd6422ae14"
         },
         "script":"76a91458b6e991b45487df810f4d96d5315da739637f1788ac"
      },
      {
         "prev_out":{
            "index":0,
            "hash":"621c6b92cc2c68b18fef3a90a3284d1263ea43e0cbce21d9ef6f51747bd215ec"
         },
         "script":"76a91458b6e991b45487df810f4d96d5315da739637f1788ac"
      },
      {
         "prev_out":{
            "index":0,
            "hash":"92a271c568aea34c3e2661db9b8fc7f0d82d90065db1b6eed1c124146ef77898"
         },
         "script":"76a91458b6e991b45487df810f4d96d5315da739637f1788ac"
      },
      {
         "prev_out":{
            "index":0,
            "hash":"99c43b144adb6d114180c11f26bc08264c806b355d96a824891ab0831c7facfd"
         },
         "script":"76a91458b6e991b45487df810f4d96d5315da739637f1788ac"
      }
   ],
   "version":1,
   "vin_sz":4,
   "hash":"6c521937d8fa889d71609ebed2e23b694cbca89778c8b8d967167e5a4c9d5b78",
   "vout_sz":3,
   "out":[
      {
         "script_string":"OP_DUP OP_HASH160 1485d9d03b41aaa9dca7d70d7f63ff4a0826100e OP_EQUALVERIFY OP_CHECKSIG",
         "address":"12sWrxRY7E7Nhmuyjbz4TtGE9jRewGqEZD",
         "value":5430,
         "script":"76a9141485d9d03b41aaa9dca7d70d7f63ff4a0826100e88ac"
      },
      {
         "script_string":"OP_RETURN 246698efc5d81b78ceadf3179316b5eb6cc5c2c347c0b7b42121a94e",
         "value":0,
         "script":"6a1c246698efc5d81b78ceadf3179316b5eb6cc5c2c347c0b7b42121a94e"
      },
      {
         "script_string":"OP_DUP OP_HASH160 58b6e991b45487df810f4d96d5315da739637f17 OP_EQUALVERIFY OP_CHECKSIG",
         "address":"1965areciqapsuL2hsia2yKkRLfAsH1smG",
         "value":6290,
         "script":"76a91458b6e991b45487df810f4d96d5315da739637f1788ac"
      }
   ]
}

**Comment by EricLarch** [comment]
The Nano supports 1 output, 1 change and 1 OP_RETURN. So if your second output is a change then yes it'll be ok. 

The Nano S doesn't have these restrictions, and you can build native app allowing powerful verifications on screen of the transaction. You are welcome to join our Developer Slack http://slack.ledger.co/ for more information.

**Comment by chris41188** [comment]
Thanks for the reply I will check out the nano s and also slack if I need further assistance
