### ISSUE TITLE
Send Payment without data doesn't work

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/ledger-wallet-api#7]
When I call 
`{ command: "send_payment", address: recipientAddress, amount: amount }`

the ledger wallet app opens, but it has a field in the form called **Data (OP_RETURN)** with a value of **undefined**.  And the send payment is unable to complete. I've tried to provide various data values to make it happy, but I can't get it to work. 

This is with LiteCoin, by the way. 

Hoping to get this resolved as I'd really love for the app to integrate with Ledger Wallet.

**Comment by ghost** [comment]
I resolved this by passing the value `3350e7ebcfbfb0660d7cfbfba8b3bfb49da1f32871b5be8597bbcbe3`
 as per shown in the PR submitted https://github.com/LedgerHQ/ledger-wallet-api/pull/10/files by 	rigelrozanski. Not sure what it is exactly doing, which is a little scary, but it makes Ledger Wallet happy.

**Comment by nerdvibe** [comment]
@rhizohm stumbled upon this issue as well.. You can pass an empty string as third parameter and it will probably do the job ;)
